import UsuarioService from "./UsuarioService";
import DadosPessoaisService from "./DadosPessoaisService";
import IndiceService from "./IndiceService";
import VersaoService from "./VersaoService";
import RelacionamentoService from "./RelacionamentoService";
import PlanoVinculadoService from "./PlanoVinculadoService";
import FichaContribPrevidencialService from "./FichaContribPrevidencialService";
import FichaSalarioContribuicaoService from "./FichaSalarioContribuicaoService";
import ProcessoBeneficioService from "./ProcessoBeneficioService";
import FichaFinancAssistidoService from "./FichaFinancAssistidoService";
import ContratoEmprestimoService from "./ContratoEmprestimoService";
import DependenteService from "./DependenteService";
import ComprovanteRendimentosService from "./ComprovanteRendimentosService";
export { UsuarioService, DadosPessoaisService, IndiceService, VersaoService, RelacionamentoService, PlanoVinculadoService, FichaContribPrevidencialService, FichaSalarioContribuicaoService, ProcessoBeneficioService, FichaFinancAssistidoService, ContratoEmprestimoService, DependenteService, ComprovanteRendimentosService };
